### ISSUE TITLE
MeCab의 morphs를 pos로 바꾸기

### ISSUE THREAD

**Issue by Nerrtica** [MacLunch/MacLunch#1]

**Comment by SNTruer** [comment]
morphs -> pos로 변경

 * ###morphs
   * forumid와 author, title, text를 bag of words로 변환 (feature : 1,000개) - 0.721
   * forumid와 author, title을 bag of words로 변환 (feature : 1,000개) - 0.712577335639
   * forumid와 author, text를 bag of words로 변환 (feature : 1,000개) - 0.721
   
   * ###pos
   * forumid와 author, title, text의 pos를 bag of words로 변환 (feature : 1,000개) - 0.728390543803
   * forumid와 author, title의 pos를 bag of words로 변환 (feature : 1,000개) - 0.704123734689
   * forumid와 author, text의 pos를 bag of words로 변환 (feature : 1,000개) - 0.720707529009
