### ISSUE TITLE
라이브러리로 변환

### ISSUE THREAD

**Issue by shaynekang** [MacLunch/MacLunch#25]
그동안 작업한 내용을 바탕으로, 가장 높은 정확도가 나오는 알고리즘을 모아 라이브러리로 뺍니다.
`lib/` 폴더에 넣으면 될 것 같고, 쓰기 편하게 클래스나 함수로 만들면 좋겠습니다.

다음의 기능이 필요하겠네요.
- 라벨값이 있는 데이터를 넣어주면 fit하기
- 라벨값이 없는 데이터를 넣어주면 predict하기
- fit한 예측모델을 저장하기(save)
- fit한 예측모델을 읽어오기(load)

다 같이 생각해서, 더 필요한 기능이 있다면 코멘트로 적어줍시다. ㅎㅎ

**Comment by SNTruer** [comment]
#29
